# Generated by Django 3.0.5 on 2020-05-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('malicious_rate', models.IntegerField(default=0)),
                ('list_data_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chartjs.Date')),
            ],
        ),
    ]
